apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
 name: notify-on-failure2
 namespace: flux-team-dev
spec:
 providerRef:
   name: rocketchat2
 eventSeverity: error
 eventSources:
   - kind: Kustomization
     name: '*'