apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: team-dev-apps
  namespace: flux-team-dev
spec:
  interval: 1m
  path: clusters/team-dev/flux-system/flux-team-dev/environment/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: team-dev-repo
    namespace: flux-team-dev
  # timeout: 2m
  # retryInterval: 30s
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: app1
  #     namespace: team-dev
